alter session set "_ORACLE_SCRIPT"=true;
CREATE ROLE admin_ang;

GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.ANGAJATI TO admin_ang;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.ANGAJATI_COMPETENTE TO admin_ang;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.COMPETENTE TO admin_ang;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.DEPARTAMENTE TO admin_ang;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.PONTAJ TO admin_ang;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.PROIECTE TO admin_ang;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.PROIECTE_COMPETENTE TO admin_ang
GRANT create session TO admin_ang;


CREATE USER admin_rh IDENTIFIED BY adminrh;
GRANT admin_ang TO admin_rh;
commit;
select * from session_roles;


---------ROL ANGAJAT------------
CREATE ROLE rol_angajat;
GRANT SELECT,UPDATE ON userDBA.ANGAJATI TO rol_angajat;
GRANT SELECT ON userDBA.ANGAJATI_COMPETENTE TO rol_angajat;
GRANT SELECT ON userDBA.COMPETENTE TO rol_angajat;
GRANT SELECT ON userDBA.DEPARTAMENTE TO rol_angajat;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.PONTAJ TO rol_angajat;
GRANT SELECT,INSERT,UPDATE,DELETE ON userDBA.PROIECTE TO rol_angajat;
GRANT create session TO rol_angajat;
