-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-11-03 23:08:41 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE angajati
  (
    ang_id            NUMBER (4) NOT NULL ,
    ang_nume          VARCHAR2 (50) NOT NULL ,
    ang_prenume       VARCHAR2 (50) NOT NULL ,
    ang_salariu       NUMBER (5) NOT NULL ,
    ang_data_angajare DATE NOT NULL ,
    ang_data_parasire DATE DEFAULT NULL ,
    dept_id           NUMBER (3) NOT NULL
  ) ;
ALTER TABLE angajati ADD CONSTRAINT angajati_PK PRIMARY KEY ( ang_id ) ;


CREATE TABLE angajati_competente
  (
    ang_id  NUMBER (4) NOT NULL ,
    comp_id NUMBER (2) NOT NULL
  ) ;
ALTER TABLE angajati_competente ADD CONSTRAINT ANGAJATI_COMPETENTE_FK_PK PRIMARY KEY ( ang_id, comp_id ) ;


CREATE TABLE competente
  (
    comp_id       NUMBER (2) NOT NULL ,
    comp_denumire VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE competente ADD CONSTRAINT competente_PK PRIMARY KEY ( comp_id ) ;


CREATE TABLE departamente
  (
    dept_id   NUMBER (3) NOT NULL ,
    dept_nume VARCHAR2 (50) DEFAULT NULL
  ) ;
ALTER TABLE departamente ADD CONSTRAINT departamente_PK PRIMARY KEY ( dept_id ) ;


CREATE TABLE pontaj
  (
    pontaj_zi        DATE NOT NULL ,
    pontaj_ora_start NUMBER (2) NOT NULL ,
    pontaj_ora_end   NUMBER (2) NOT NULL ,
    ang_id           NUMBER (4) NOT NULL ,
    pro_id           NUMBER (3) NOT NULL
  ) ;
ALTER TABLE pontaj ADD CONSTRAINT pontaj_PK PRIMARY KEY ( ang_id ) ;


CREATE TABLE proiecte
  (
    pro_id            NUMBER (3) NOT NULL ,
    pro_nume          VARCHAR2 (50) NOT NULL ,
    pro_ore_estimate  NUMBER (4) NOT NULL ,
    pro_ore_efectuate NUMBER (4) NOT NULL ,
    pro_stadiu        VARCHAR2 (7) DEFAULT 'deschis'
  ) ;
ALTER TABLE proiecte ADD CHECK ( pro_stadiu IN ('depasit', 'deschis', 'inchis')) ;
ALTER TABLE proiecte ADD CONSTRAINT proiecte_PK PRIMARY KEY ( pro_id ) ;


CREATE TABLE proiecte_competente
  (
    pro_id  NUMBER (3) NOT NULL ,
    comp_id NUMBER (2) NOT NULL
  ) ;
ALTER TABLE proiecte_competente ADD CONSTRAINT PROIECTE_COMPETENTE_FK_PK PRIMARY KEY ( pro_id, comp_id ) ;


CREATE TABLE utilizatori
  (
    utilizator_parola VARCHAR2 (20) NOT NULL ,
    ang_id            NUMBER (3) NOT NULL ,
    utilizator_tip    VARCHAR2 (15) DEFAULT 'utilizator'
  ) ;
ALTER TABLE utilizatori ADD CHECK ( utilizator_tip IN ('administrator', 'utilizator')) ;
CREATE UNIQUE INDEX utilizatori__IDX ON utilizatori ( ang_id ASC ) ;


ALTER TABLE angajati_competente ADD CONSTRAINT FK_ASS_1 FOREIGN KEY ( ang_id ) REFERENCES angajati ( ang_id ) NOT DEFERRABLE ;

ALTER TABLE angajati_competente ADD CONSTRAINT FK_ASS_2 FOREIGN KEY ( comp_id ) REFERENCES competente ( comp_id ) NOT DEFERRABLE ;

ALTER TABLE proiecte_competente ADD CONSTRAINT FK_ASS_6 FOREIGN KEY ( pro_id ) REFERENCES proiecte ( pro_id ) NOT DEFERRABLE ;

ALTER TABLE proiecte_competente ADD CONSTRAINT FK_ASS_7 FOREIGN KEY ( comp_id ) REFERENCES competente ( comp_id ) NOT DEFERRABLE ;

ALTER TABLE angajati ADD CONSTRAINT anagajati_departamente_FK FOREIGN KEY ( dept_id ) REFERENCES departamente ( dept_id ) NOT DEFERRABLE ;

ALTER TABLE pontaj ADD CONSTRAINT pontaj_anagajati_FK FOREIGN KEY ( ang_id ) REFERENCES angajati ( ang_id ) NOT DEFERRABLE ;

ALTER TABLE pontaj ADD CONSTRAINT pontaj_proiecte_FK FOREIGN KEY ( pro_id ) REFERENCES proiecte ( pro_id ) NOT DEFERRABLE ;

ALTER TABLE utilizatori ADD CONSTRAINT utilizatori_anagajati_FK FOREIGN KEY ( ang_id ) REFERENCES angajati ( ang_id ) NOT DEFERRABLE ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
